purpur.repository=https://github.com/PurpurMC/Purpur
purpur.branch=ver/26.2
purpur.commit=3f5d9c0e80b56812c1694e014d44fabf540a4cad
paper.repository=https://github.com/PaperMC/Paper
paper.commit=e5fe71723e2ffde7cc9fafc085ac3bb73e63175e
