group = dev.quantumspigot

mcVersion = 26.2
apiVersion = 26.2
channel=EXPERIMENTAL
paperCommit = e5fe71723e2ffde7cc9fafc085ac3bb73e63175e

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx4G -XX:MaxMetaspaceSize=1G
org.gradle.workers.max = 4
